"""Reliable AI Task Streaming library for FastAPI.

This package provides infrastructure for long-running AI tasks with
WebSocket and HTTP polling support, event replay, and idempotency.
"""

from .action_receipt_store import ActionReceiptStore
from .dependencies import (
    get_auth_context_resolver,
    get_metrics_sink,
    get_ownership_policy,
    get_readiness_probe,
    get_task_action_service,
    get_task_cancellation_service,
    get_task_creation_service,
    get_task_polling_service,
    get_upload_policy,
    get_websocket_subscription_service,
    resolve_http_auth_context,
    resolve_ws_auth_context,
)
from .errors import (
    AuthenticationError,
    IdempotencyConflictError,
    InvalidRequestError,
    InvalidTaskStateError,
    TaskAlreadyTerminalError,
    TaskBridgeError,
    TaskConflictError,
    TaskNotFoundError,
    TaskOwnershipError,
    TaskSubmissionError,
    UploadValidationError,
)
from .event_store import EventStore, RedisEventStoreSettings, RedisStreamEventStore
from .fakes import DeterministicFakeExecutor
from .models import (
    AuthContext,
    CancelTaskCommand,
    CancelTaskResult,
    CancelTaskStatus,
    ErrorResponse,
    HealthResponse,
    HttpCancelTaskRequest,
    HttpSubmitActionRequest,
    HttpTaskCreateRequest,
    PollEventsResult,
    ReadinessResponse,
    ResumeHandoffStatus,
    SubmitActionCommand,
    SubmitActionResult,
    SubmitActionResultStatus,
    TaskActionReceipt,
    TaskActionReceiptStatus,
    TaskAttachment,
    TaskCreateCommand,
    TaskCreatedResult,
    TaskEvent,
    TaskEventType,
    TaskRecord,
    TaskStatus,
    TaskSuspensionRecord,
    TaskSuspensionStatus,
    WebSocketHeartbeat,
    WebSocketSubscribeRequest,
    WebSocketSubscriptionConfirmed,
    ensure_transition,
    same_idempotency_payload,
)
from .observability import (
    MetricsSink,
    NoOpMetricsSink,
    NoOpTransportDiagnosticsSink,
    TransportDiagnosticsSink,
)
from .readiness import (
    AlwaysReadyProbe,
    CompositeReadinessProbe,
    ExecutorReadinessProbe,
    ReadinessProbe,
    RedisReadinessProbe,
)
from .routes_http import HttpRouteSettings, build_http_router, install_http_exception_handlers
from .routes_ws import WebSocketRouteSettings, build_ws_router
from .security import (
    AllowAllUploadPolicy,
    AuthContextResolver,
    DenyAllAccessPolicy,
    OwnershipPolicy,
    UploadPolicy,
)
from .services import (
    TaskActionService,
    TaskCancellationService,
    TaskCreationService,
    TaskPollingService,
    TaskResumeReconciliationService,
    TaskResumeService,
    TaskRetentionService,
    WebSocketSubscriptionService,
)
from .stream_runtime import build_sse_stream_response, sse_event_generator
from .stream_settings import SseStreamSettings, StreamRuntimeSettings, WebSocketStreamSettings
from .suspension_store import SuspensionStore
from .task_registry import TaskRegistry
from .worker import TaskExecutor

__all__ = [
    "AuthContext",
    "AuthContextResolver",
    "AllowAllUploadPolicy",
    "ActionReceiptStore",
    "AlwaysReadyProbe",
    "AuthenticationError",
    "CancelTaskCommand",
    "HttpCancelTaskRequest",
    "HttpSubmitActionRequest",
    "HttpTaskCreateRequest",
    "CancelTaskResult",
    "CancelTaskStatus",
    "CompositeReadinessProbe",
    "DeterministicFakeExecutor",
    "DenyAllAccessPolicy",
    "ErrorResponse",
    "ExecutorReadinessProbe",
    "EventStore",
    "HealthResponse",
    "HttpRouteSettings",
    "RedisEventStoreSettings",
    "RedisStreamEventStore",
    "IdempotencyConflictError",
    "MetricsSink",
    "NoOpMetricsSink",
    "NoOpTransportDiagnosticsSink",
    "InvalidTaskStateError",
    "InvalidRequestError",
    "OwnershipPolicy",
    "PollEventsResult",
    "ReadinessProbe",
    "ReadinessResponse",
    "RedisReadinessProbe",
    "ResumeHandoffStatus",
    "SubmitActionCommand",
    "SubmitActionResult",
    "SubmitActionResultStatus",
    "TaskAlreadyTerminalError",
    "TaskAttachment",
    "TaskActionReceipt",
    "TaskActionReceiptStatus",
    "TaskActionService",
    "TaskRetentionService",
    "TaskResumeReconciliationService",
    "TaskBridgeError",
    "TaskCancellationService",
    "TaskConflictError",
    "TaskCreateCommand",
    "TaskCreatedResult",
    "TaskCreationService",
    "TaskEvent",
    "TaskEventType",
    "TaskExecutor",
    "TaskNotFoundError",
    "TaskOwnershipError",
    "TaskSubmissionError",
    "TaskSuspensionRecord",
    "TaskSuspensionStatus",
    "TaskResumeService",
    "SuspensionStore",
    "SseStreamSettings",
    "StreamRuntimeSettings",
    "UploadValidationError",
    "TransportDiagnosticsSink",
    "TaskPollingService",
    "TaskRecord",
    "TaskRegistry",
    "TaskStatus",
    "UploadPolicy",
    "WebSocketHeartbeat",
    "WebSocketRouteSettings",
    "WebSocketSubscribeRequest",
    "WebSocketSubscriptionConfirmed",
    "WebSocketSubscriptionService",
    "WebSocketStreamSettings",
    "build_http_router",
    "build_sse_stream_response",
    "build_ws_router",
    "ensure_transition",
    "get_auth_context_resolver",
    "get_metrics_sink",
    "get_readiness_probe",
    "get_ownership_policy",
    "get_task_action_service",
    "get_task_cancellation_service",
    "get_task_creation_service",
    "get_task_polling_service",
    "get_upload_policy",
    "get_websocket_subscription_service",
    "install_http_exception_handlers",
    "resolve_http_auth_context",
    "resolve_ws_auth_context",
    "same_idempotency_payload",
    "sse_event_generator",
]
